### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by kitadani** [fedech/dashlearning#1]
I ran adaptation_sim.
However,I receive the following error.

>>
Error using load
Unable to read file './Qmats/facl_p1s2ds.mat'. No such file or directory.

Error in adaptation_sim (line 30)
    load('./Qmats/facl_p1s2ds.mat'); 
>>

What is Qmats file?
What is in this file?

**Comment by fedech** [comment]
The file contained the pre-trained Q matrices, which you can create using the markov_sim, markov_faq and markov_parallel files. I shouldn't have left adaptation_sim there, I removed it from the repo since it creates confusion (the correct main files are the ones that start with markov_)

**Comment by kitadani** [comment]
Thank you for answering the question.
